---
# tasks file for vault
- name: Add Hashicorp Repository key 
  apt_key:
    url: https://apt.releases.hashicorp.com/gpg 
    state: present

- name: Add Hashicorp Repository
  apt_repository:
    repo: deb [arch=amd64] https://apt.releases.hashicorp.com buster main
    state: present

- name: Install Vault
  package:
    name:
      - vault 
    state: present
    update_cache: yes
