---
# tasks file for docker
- name: Install base dependencies
  package:
    name:
      - apt-transport-https 
      - ca-certificates
      - curl 
      - gnupg2 
      - software-properties-common
      - tcpdump
      - wget
      - telnet
      - vim
      - dnsutils
      - mtr-tiny
      - python3-pip
    state: present
    update_cache: yes
